# Generated by Django 5.0.6 on 2024-06-05 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(max_length=15, unique=True)),
                ('admin_email', models.CharField(max_length=50, unique=True)),
                ('uuid_token', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('physics', 'Physics'), ('chemistry', 'Chemistry'), ('medicine', 'Physiology or Medicine'), ('peace', 'Peace'), ('literature', 'Literature'), ('economics', 'Economics Sciences')], default='Chemistry', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('fullname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255, null=True)),
                ('abbrevative', models.CharField(max_length=50, null=True)),
                ('dateofbirth', models.DateField(null=True)),
                ('dateofdeath', models.DateField(null=True)),
                ('gender', models.CharField(max_length=25, null=True)),
                ('affiliation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.affiliation')),
                ('cityborn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='born_city', to='myapp.city')),
                ('citydied', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='died_city', to='myapp.city')),
                ('countryborn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='born_country', to='myapp.country')),
                ('countrydied', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='died_country', to='myapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Laureates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardyear', models.CharField(max_length=4)),
                ('motivation', models.CharField(max_length=255)),
                ('overallmotivation', models.CharField(max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category')),
                ('sharewith', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_laureates', to='myapp.winner')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laureates', to='myapp.winner')),
            ],
        ),
    ]
