/**
 * For self note only
 * This file is generated by react-create-app. 
 * Web vitals are for sending any of results to an analytics endpoint to measure and track real user performance on your site. This is a google tool to measure real user on using your site. Use it at your own risk. 
 * See Web-Vital : (https://github.com/GoogleChrome/web-vitals) 
 * See React measuring performance : (https://create-react-app.dev/docs/measuring-performance/)
 * @param {Any} onPerfEntry - place any items, include body, website, anything metrics related written as a function
 */
const reportWebVitals = onPerfEntry => {
  if (onPerfEntry && onPerfEntry instanceof Function) {
    import('web-vitals').then(({ getCLS, getFID, getFCP, getLCP, getTTFB }) => {
      getCLS(onPerfEntry);
      getFID(onPerfEntry);
      getFCP(onPerfEntry);
      getLCP(onPerfEntry);
      getTTFB(onPerfEntry);
    });
  }
};

export default reportWebVitals;
